CREATE INDEX "scout_facility_organization_id_idx" ON "scout_facility" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_facility_area_facility_id_idx" ON "scout_facility_area" USING btree ("facility_id");--> statement-breakpoint
CREATE INDEX "scout_facility_map_object_facility_area_id_idx" ON "scout_facility_map_object" USING btree ("facility_area_id");--> statement-breakpoint
CREATE INDEX "scout_inventory_item_organization_id_idx" ON "scout_inventory_item" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_inventory_order_item_id_idx" ON "scout_inventory_order" USING btree ("item_id");--> statement-breakpoint
CREATE INDEX "scout_invite_organization_id_idx" ON "scout_invite" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_invite_email_idx" ON "scout_invite" USING btree ("email");--> statement-breakpoint
CREATE INDEX "scout_membership_user_id_idx" ON "scout_membership" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "scout_membership_organization_id_idx" ON "scout_membership" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_monitoring_threshold_organization_id_idx" ON "scout_monitoring_threshold" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_observation_photo_observation_id_idx" ON "scout_observation_photo" USING btree ("observation_id");--> statement-breakpoint
CREATE INDEX "scout_observation_photo_pest_event_id_idx" ON "scout_observation_photo" USING btree ("pest_event_id");--> statement-breakpoint
CREATE INDEX "scout_pest_event_facility_id_idx" ON "scout_pest_event" USING btree ("facility_id");--> statement-breakpoint
CREATE INDEX "scout_pest_event_facility_area_id_idx" ON "scout_pest_event" USING btree ("facility_area_id");--> statement-breakpoint
CREATE INDEX "scout_pest_event_status_idx" ON "scout_pest_event" USING btree ("status");--> statement-breakpoint
CREATE INDEX "scout_observation_organization_id_idx" ON "scout_observation" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_observation_facility_area_id_idx" ON "scout_observation" USING btree ("facility_area_id");--> statement-breakpoint
CREATE INDEX "scout_observation_promoted_pest_event_id_idx" ON "scout_observation" USING btree ("promoted_pest_event_id");--> statement-breakpoint
CREATE INDEX "scout_task_organization_id_idx" ON "scout_task" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_task_facility_id_idx" ON "scout_task" USING btree ("facility_id");--> statement-breakpoint
CREATE INDEX "scout_task_facility_area_id_idx" ON "scout_task" USING btree ("facility_area_id");--> statement-breakpoint
CREATE INDEX "scout_task_pest_event_id_idx" ON "scout_task" USING btree ("pest_event_id");--> statement-breakpoint
CREATE INDEX "scout_task_assignee_user_id_idx" ON "scout_task" USING btree ("assignee_user_id");--> statement-breakpoint
CREATE INDEX "scout_task_status_idx" ON "scout_task" USING btree ("status");--> statement-breakpoint
CREATE INDEX "scout_trap_reading_trap_id_idx" ON "scout_trap_reading" USING btree ("trap_id");--> statement-breakpoint
CREATE INDEX "scout_trap_threshold_organization_id_idx" ON "scout_trap_threshold" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "scout_trap_facility_id_idx" ON "scout_trap" USING btree ("facility_id");--> statement-breakpoint
CREATE INDEX "scout_trap_facility_area_id_idx" ON "scout_trap" USING btree ("facility_area_id");--> statement-breakpoint
CREATE INDEX "scout_treatment_facility_id_idx" ON "scout_treatment" USING btree ("facility_id");--> statement-breakpoint
CREATE INDEX "scout_treatment_pest_event_id_idx" ON "scout_treatment" USING btree ("pest_event_id");--> statement-breakpoint
CREATE INDEX "scout_treatment_inventory_item_id_idx" ON "scout_treatment" USING btree ("inventory_item_id");