"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { CANVAS_TEXT } from "@/lib/canvas-text-scale";
import { SEVERITY_COLOR, SEVERITY_TEXT_COLOR, type Severity } from "@/lib/colors";
import { pointInShape } from "@/lib/map-zones";
import { queuedFetch } from "@/lib/offline-queue";
import { displayNameForPestSpecies } from "@/lib/treatments-catalog";
import { useTheme } from "@/app/app/ThemeProvider";

// Plain SVG + pointer events -- Konva/react-konva were removed entirely
// (Simon, 2026-09-07: "delete fucking konva ... it should not be doing
// anything in the desktop app"). This is a from-scratch rewrite, not a
// port: no <canvas>, no native "canvas" package SSR workaround (see the
// now-deleted MapEditorClient.tsx), and rotation editing is dropped --
// zones are generated by LayoutPicker's presets as plain axis-aligned
// rects (freehand drawing was already retired), so a rotate handle had no
// real caller left. A legacy hand-drawn zone that already has a stored
// rotation still renders rotated; there's just no UI to change it anymore.
//
// Freehand shape creation stays retired per Simon's earlier call
// (map-redesign-plan.md, 2026-08-21) -- this still renders/repositions/
// resizes/deletes whatever shapes already exist and handles pin
// placement, never creates a brand-new arbitrary shape from scratch.
type ShapeType = "rect" | "circle" | "polygon" | "line" | "label";

interface Geometry {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
  rotation?: number;
  points?: number[];
}

interface MapObject {
  id: string;
  shapeType: ShapeType;
  geometry: Geometry;
  style: { fill?: string; stroke?: string; strokeWidth?: number } | null;
  label: string | null;
  zIndex: number;
}

interface Area {
  id: string;
  name: string;
  backgroundImageUrl: string | null;
  backgroundScale: number | null;
}

interface PestEvent {
  id: string;
  x: number | null;
  y: number | null;
  pestSpecies: string;
  severity: Severity;
  status: "active" | "resolved";
  notes: string | null;
  createdAt: string;
  lastTreatedAt: string | null;
  trend: "up" | "down" | "stable" | null;
}

const FOLLOW_UP_AFTER_DAYS = 3;
const RECENTLY_TREATED_DAYS = 7;
const DAY_MS = 86_400_000;
function needsFollowUp(createdAt: string): boolean {
  return Date.now() - new Date(createdAt).getTime() > FOLLOW_UP_AFTER_DAYS * DAY_MS;
}
function wasRecentlyTreated(lastTreatedAt: string | null): boolean {
  return lastTreatedAt != null && Date.now() - new Date(lastTreatedAt).getTime() < RECENTLY_TREATED_DAYS * DAY_MS;
}
// Bigger pin = worse severity -- one of the two always-on visual channels
// (color being the other), per the "glanceable, not click-to-learn" design
// direction. Ring/halo/arrow are secondary accents, only drawn when there's
// something to say, not competing dimensions on every pin.
const SEVERITY_RADIUS: Record<Severity, number> = { low: 7, moderate: 9.5, high: 12, severe: 15 };
// Largest severe pin's radius (15) doubled -- comfortably covers two
// severe pins dropped at the exact same bay coordinate (the common case:
// both inherit the same pin from a shared location picker) without also
// catching two genuinely different, merely nearby bays.
const OVERLAP_PX = 30;
// Minimum size a resize drag can shrink a shape to -- small enough to feel
// unrestrictive, large enough that a zone never collapses to something
// impossible to grab again.
const MIN_RECT_SIZE = 10;
const MIN_RADIUS = 6;

const CANVAS_WIDTH = 900;
const CANVAS_HEIGHT = 600;
// SVG can read CSS custom properties directly, unlike a <canvas> -- these
// still exist as a fixed light/dark pair (rather than inline var(...)
// everywhere) only because the trend-arrow/line colors need a plain string
// to compare against elsewhere in this file; kept for continuity with the
// existing --map-blue/--map-blue-soft/--text tokens in globals.css.
const CANVAS_COLORS = {
  light: { mapBlue: "#2f7fc4", mapBlueFill: "#eaf3fb", line: "#1c2431", trendUp: "#c1502e", trendDown: "#2f8f6e" },
  dark: { mapBlue: "#7ec4f0", mapBlueFill: "#bfe3fa", line: "#ffffff", trendUp: "#ce5d40", trendDown: "#4e9e86" },
} as const;
const SEVERITY_RANK: Record<Severity, number> = { low: 0, moderate: 1, high: 2, severe: 3 };

// Every drawn zone is the same calm light blue by default -- color is a
// hotspot signal, not a decoration a grower picks per-shape. If an active
// pest event's pin falls inside a zone, that zone tints to the worst
// severity found inside it instead.
function hotspotSeverity(obj: MapObject, events: PestEvent[]): Severity | null {
  let worst: Severity | null = null;
  for (const ev of events) {
    if (ev.status !== "active" || ev.x == null || ev.y == null) continue;
    if (!pointInShape(ev.x, ev.y, obj.shapeType, obj.geometry)) continue;
    if (!worst || SEVERITY_RANK[ev.severity] > SEVERITY_RANK[worst]) worst = ev.severity;
  }
  return worst;
}

// getScreenCTM/matrixTransform accounts for however the SVG is actually
// scaled on screen (viewBox meet-scaling, device pixel ratio) -- same
// pattern LocationPicker.tsx's svgPointFromEvent uses. Returns real
// 900x600-canvas-space coordinates regardless of the SVG's rendered size.
function svgPoint(svg: SVGSVGElement, clientX: number, clientY: number): { x: number; y: number } {
  const pt = svg.createSVGPoint();
  pt.x = clientX;
  pt.y = clientY;
  const ctm = svg.getScreenCTM();
  if (!ctm) return { x: 0, y: 0 };
  const p = pt.matrixTransform(ctm.inverse());
  return { x: p.x, y: p.y };
}

type DragKind = "move" | "resize";
interface DragState {
  kind: DragKind;
  pointerId: number;
  startPointer: { x: number; y: number };
  startGeom: Geometry;
}

export default function MapEditor({
  facilityId,
  area,
  initialObjects,
  initialPestEvents,
}: {
  facilityId: string;
  area: Area;
  initialObjects: MapObject[];
  initialPestEvents: PestEvent[];
}) {
  const router = useRouter();
  const { theme } = useTheme();
  const { mapBlue: MAP_BLUE, mapBlueFill: MAP_BLUE_FILL, line: CANVAS_LINE, trendUp: CANVAS_TREND_UP, trendDown: CANVAS_TREND_DOWN } = CANVAS_COLORS[theme];
  const [mode, setMode] = useState<"view" | "edit">("view");
  const [objects, setObjects] = useState<MapObject[]>(initialObjects);
  const [pestEvents, setPestEvents] = useState<PestEvent[]>(initialPestEvents);
  const [tool, setTool] = useState<"select" | "pest">("select");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [pestFormPos, setPestFormPos] = useState<{ x: number; y: number } | null>(null);
  const [pestSpecies, setPestSpecies] = useState("");
  const [pestSeverity, setPestSeverity] = useState<Severity>("moderate");
  const [selectedEvent, setSelectedEvent] = useState<PestEvent | null>(null);
  // Two hotspots pinned to the same row/bench render as overlapping circles
  // -- a click only ever reaches the topmost one, so tapping the spot
  // silently always opened whichever happened to render last, with no way
  // to reach the other (ticket found in QA, 2026-09-03). A small picker
  // instead of navigating straight through whenever more than one active
  // event's pin is within OVERLAP_PX of the tapped one.
  const [overlapPicker, setOverlapPicker] = useState<PestEvent[] | null>(null);

  const svgRef = useRef<SVGSVGElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const dragRef = useRef<DragState | null>(null);
  const dragObjectId = useRef<string | null>(null);

  // The canvas's internal coordinate system stays a fixed 900x600 (every
  // shape's x/y/width/height is stored in that space) -- only how it's
  // *rendered* shrinks to fit narrower viewports. The SVG's own viewBox
  // does that scaling for free (unlike Konva's Stage, which needed manual
  // scaleX/scaleY on every drawn coordinate): only the wrapper's CSS
  // width/height need the scale multiplication below, everything drawn
  // inside stays in plain 900x600 canvas-space.
  const [baseScale, setBaseScale] = useState(1);
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const observer = new ResizeObserver(([entry]) => {
      // Capped at 1.4x, not 1x -- the map should fill most of its card on
      // a normal desktop width, not stay pinned to 900px with dead space
      // around it, but an ultrawide monitor shouldn't blow it up absurdly.
      setBaseScale(Math.min(1.4, entry.contentRect.width / CANVAS_WIDTH));
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // User-driven zoom multiplier on top of the responsive baseScale above --
  // separate state so a container resize (which recomputes baseScale) never
  // clobbers a zoom level the grower is actively using. Page-wide native
  // pinch/double-tap zoom is disabled (app/layout.tsx's viewport export,
  // ticket C2), so this + the touch pinch handler below are what replace it
  // specifically for the map.
  const MIN_ZOOM = 1;
  const MAX_ZOOM = 3;
  const [zoom, setZoom] = useState(1);
  const scale = baseScale * zoom;
  const pinchState = useRef<{ distance: number; zoom: number } | null>(null);

  function touchDistance(touches: React.TouchList): number {
    const [a, b] = [touches[0], touches[1]];
    return Math.hypot(b.clientX - a.clientX, b.clientY - a.clientY);
  }

  function handleTouchMove(e: React.TouchEvent<HTMLDivElement>) {
    const touches = e.touches;
    if (touches.length !== 2) {
      pinchState.current = null;
      return;
    }
    const distance = touchDistance(touches);
    if (!pinchState.current) {
      pinchState.current = { distance, zoom };
      return;
    }
    const next = (pinchState.current.zoom * distance) / pinchState.current.distance;
    setZoom(Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, next)));
  }

  function handleTouchEnd(e: React.TouchEvent<HTMLDivElement>) {
    if (e.touches.length < 2) pinchState.current = null;
  }

  const base = `/api/facilities/${facilityId}/areas/${area.id}`;
  const eventsBase = `/api/facilities/${facilityId}/pest-events`;

  async function updateGeometry(id: string, geometry: Geometry) {
    setObjects((prev) => prev.map((o) => (o.id === id ? { ...o, geometry } : o)));
    await queuedFetch(`${base}/objects/${id}`, { geometry }, "Map edit", "PATCH");
  }

  async function deleteSelected() {
    if (!selectedId) return;
    // A glove brush on this button used to delete a bench or zone outright
    // with no way back -- CatalogClient and TeamClient already confirm
    // before their own destructive actions, this just matches that
    // existing house standard (Airtable ticket recfnsVgXC5RlyBiI).
    const target = objects.find((o) => o.id === selectedId);
    if (!confirm(`Delete ${target?.label ? `"${target.label}"` : "this map object"}? This can't be undone.`)) return;
    // Queued rather than a bare fetch (Airtable ticket rec7LEsgfHWQ8glss) --
    // the DELETE route ignores its body entirely, so {} is just a
    // placeholder queuedFetch's signature requires. Removed from local
    // state either way: a queued delete is confirmed intent, not something
    // to leave half-applied in the UI while it waits to sync.
    const result = await queuedFetch(`${base}/objects/${selectedId}`, {}, "Delete map object", "DELETE");
    if (result.ok) setObjects((prev) => prev.filter((o) => o.id !== selectedId));
    setSelectedId(null);
  }

  async function submitPestEvent() {
    if (!pestFormPos || !pestSpecies.trim()) return;
    // Queued rather than a bare fetch (Airtable ticket rec7LEsgfHWQ8glss) --
    // a pest event pinned on the map while offline used to be lost outright
    // with no error shown. Queued: no server-generated id exists yet to add
    // a real pin for, so the form just closes the same way it does on
    // success rather than inventing a fake row -- the pin appears once the
    // queue syncs and this page is next loaded.
    const result = await queuedFetch(
      eventsBase,
      { facilityAreaId: area.id, x: pestFormPos.x, y: pestFormPos.y, pestSpecies: pestSpecies.trim(), severity: pestSeverity },
      "Pest event"
    );
    if (result.ok && !result.queued) {
      setPestEvents((prev) => [...prev, result.data as (typeof prev)[number]]);
    }
    setPestFormPos(null);
    setPestSpecies("");
    setPestSeverity("moderate");
    setTool("select");
  }

  async function resolveSelectedEvent() {
    if (!selectedEvent) return;
    // Queued rather than a bare fetch (Airtable ticket rec7LEsgfHWQ8glss).
    // Optimistic either way (same as the online branch already was) -- a
    // queued resolve is confirmed intent, not something to leave the map
    // showing as still-active while it waits to sync.
    const result = await queuedFetch(`${eventsBase}/${selectedEvent.id}`, { status: "resolved" }, "Resolve pest event", "PATCH");
    if (result.ok) {
      setPestEvents((prev) => prev.map((ev) => (ev.id === selectedEvent.id ? { ...ev, status: "resolved" } : ev)));
    }
    setSelectedEvent(null);
  }

  async function deleteSelectedEvent() {
    if (!selectedEvent) return;
    // Same confirm-before-destructive-action standard as deleteSelected
    // above (Airtable ticket recfnsVgXC5RlyBiI) -- a glove brush here used
    // to delete a pest event and its whole history with zero confirmation.
    // The comment thread and any photos are named explicitly here
    // (Airtable ticket recyEgh3n4vqZTqmw) -- the DELETE route cleans up
    // photos/blobs and records the deletion, but the comment thread
    // genuinely, permanently goes with it, and this is the one place that
    // says so before it happens.
    if (
      !confirm(
        `Delete this ${displayNameForPestSpecies(selectedEvent.pestSpecies)} event? This also permanently deletes its comment thread and any photos. This can't be undone.`
      )
    )
      return;
    const result = await queuedFetch(`${eventsBase}/${selectedEvent.id}`, {}, "Delete pest event", "DELETE");
    if (result.ok) {
      setPestEvents((prev) => prev.filter((ev) => ev.id !== selectedEvent.id));
    }
    setSelectedEvent(null);
  }

  async function handleBackgroundUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    const form = new FormData();
    form.append("file", file);
    const res = await fetch(`${base}/background`, { method: "POST", body: form });
    setUploading(false);
    if (res.ok) window.location.reload(); // simplest way to refresh the loaded background image
  }

  function handleBackgroundPointerDown(e: React.PointerEvent<SVGRectElement>) {
    if (mode === "view") return; // view mode has no selection tools -- pins handle their own click
    if (tool === "select") {
      setSelectedId(null);
      setSelectedEvent(null);
      return;
    }
    if (tool === "pest") {
      const svg = svgRef.current;
      if (!svg) return;
      setPestFormPos(svgPoint(svg, e.clientX, e.clientY));
    }
  }

  function beginShapeDrag(e: React.PointerEvent, objId: string, kind: DragKind, startGeom: Geometry) {
    if (mode !== "edit" || tool !== "select") return;
    e.stopPropagation();
    const svg = svgRef.current;
    if (!svg) return;
    (e.target as Element).setPointerCapture(e.pointerId);
    dragObjectId.current = objId;
    dragRef.current = { kind, pointerId: e.pointerId, startPointer: svgPoint(svg, e.clientX, e.clientY), startGeom };
    setSelectedId(objId);
  }

  function onShapePointerMove(e: React.PointerEvent) {
    const drag = dragRef.current;
    const objId = dragObjectId.current;
    if (!drag || !objId || drag.pointerId !== e.pointerId) return;
    const svg = svgRef.current;
    if (!svg) return;
    const p = svgPoint(svg, e.clientX, e.clientY);
    const dx = p.x - drag.startPointer.x;
    const dy = p.y - drag.startPointer.y;
    const obj = objects.find((o) => o.id === objId);
    if (!obj) return;
    let next: Geometry;
    if (drag.kind === "move") {
      next =
        obj.shapeType === "polygon" && drag.startGeom.points
          ? { ...drag.startGeom, points: drag.startGeom.points.map((v, i) => (i % 2 === 0 ? v + dx : v + dy)) }
          : { ...drag.startGeom, x: (drag.startGeom.x ?? 0) + dx, y: (drag.startGeom.y ?? 0) + dy };
    } else if (obj.shapeType === "rect") {
      next = { ...drag.startGeom, width: Math.max(MIN_RECT_SIZE, (drag.startGeom.width ?? 0) + dx), height: Math.max(MIN_RECT_SIZE, (drag.startGeom.height ?? 0) + dy) };
    } else if (obj.shapeType === "circle") {
      next = { ...drag.startGeom, radius: Math.max(MIN_RADIUS, (drag.startGeom.radius ?? 0) + dx) };
    } else {
      return;
    }
    setObjects((prev) => prev.map((o) => (o.id === objId ? { ...o, geometry: next } : o)));
  }

  function onShapePointerUp(e: React.PointerEvent) {
    const drag = dragRef.current;
    const objId = dragObjectId.current;
    dragRef.current = null;
    dragObjectId.current = null;
    if (!drag || !objId || drag.pointerId !== e.pointerId) return;
    const obj = objects.find((o) => o.id === objId);
    if (obj) updateGeometry(objId, obj.geometry);
  }

  return (
    <div ref={containerRef} className="flex flex-col gap-3">
      <div className="flex items-center justify-end">
        <button
          onClick={() => {
            setMode((m) => (m === "view" ? "edit" : "view"));
            setSelectedId(null);
            setSelectedEvent(null);
            setTool("select");
          }}
          className={`rounded-md border px-3 py-1.5 text-sm ${
            mode === "edit" ? "border-[var(--accent-text)] text-[var(--accent-text)]" : "border-[var(--border)] text-[var(--text-dim)]"
          }`}
        >
          {mode === "edit" ? "Done editing" : "Edit site layout"}
        </button>
      </div>

      {/* Precision drag/resize editing is genuinely hard one-handed on a
          phone -- a deliberate, confirmed call (spike rec: no code gate
          exists or should exist, since a tablet/laptop touchscreen can be
          perfectly fine; this is just an honest heads-up on the narrow-
          viewport case, not a block). The abstract bay-bar heatmap on the
          dashboard covers day-to-day mobile use instead. */}
      {mode === "edit" && (
        <div className="card p-3 text-xs text-[var(--text-dim)] lg:hidden">Precise layout editing works best on a larger screen.</div>
      )}

      {mode === "edit" && (
        <div className="flex flex-wrap items-center gap-2">
          {(["select", "pest"] as const).map((t) => (
            <button
              key={t}
              onClick={() => {
                setTool(t);
                setPestFormPos(null);
              }}
              className={`rounded-md border px-3 py-1.5 text-sm capitalize ${
                tool === t ? "border-[var(--accent-text)] text-[var(--accent-text)]" : "border-[var(--border)] text-[var(--text-dim)]"
              }`}
            >
              {t === "pest" ? "Pest event" : t}
            </button>
          ))}
          {selectedId && (
            <button onClick={deleteSelected} className="min-h-11 rounded-md border border-[var(--danger)] px-3 text-sm text-[var(--danger)]">
              Delete selected
            </button>
          )}
          <label className="ml-auto cursor-pointer rounded-md border border-[var(--border)] px-3 py-1.5 text-sm text-[var(--text-dim)]">
            {uploading ? "Uploading…" : "Upload reference image (blueprint or aerial photo)"}
            <input type="file" accept="image/*" className="hidden" onChange={handleBackgroundUpload} />
          </label>
        </div>
      )}

      {/* Explicit pixel size, not "shrink to fit content" -- this div is a
          flex-column child, and flex's default align-items:stretch would
          otherwise stretch it to the full width of its parent (which can be
          wider than the SVG's actual rendered size), leaving the map --
          and everything drawn on it -- pushed into the left portion of a
          too-wide bordered frame. */}
      {/* Zoom buttons are the primary control (reliable on every device);
          the wrapper below also handles real two-finger pinch on touch
          devices, both replacing the native pinch this page disables
          (ticket C2). overflow-auto lets a zoomed-in map be panned by
          scroll/drag, same as any oversized scrollable content. */}
      <div className="flex items-center gap-2 self-end">
        <button
          type="button"
          onClick={() => setZoom((z) => Math.max(MIN_ZOOM, z - 0.25))}
          disabled={zoom <= MIN_ZOOM}
          className="rounded-md border border-[var(--border)] px-2.5 py-1 text-sm text-[var(--text-dim)] disabled:opacity-40"
        >
          −
        </button>
        <span className="label-mono w-10 text-center">{Math.round(zoom * 100)}%</span>
        <button
          type="button"
          onClick={() => setZoom((z) => Math.min(MAX_ZOOM, z + 0.25))}
          disabled={zoom >= MAX_ZOOM}
          className="rounded-md border border-[var(--border)] px-2.5 py-1 text-sm text-[var(--text-dim)] disabled:opacity-40"
        >
          +
        </button>
      </div>

      <div className="max-w-full overflow-auto">
        <div
          className="relative map-canvas-frame"
          style={{ width: CANVAS_WIDTH * scale, height: CANVAS_HEIGHT * scale }}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          <div className="map-canvas-grid" />
          <svg
            ref={svgRef}
            viewBox={`0 0 ${CANVAS_WIDTH} ${CANVAS_HEIGHT}`}
            width={CANVAS_WIDTH * scale}
            height={CANVAS_HEIGHT * scale}
            className="block"
          >
            {area.backgroundImageUrl && (
              <image href={area.backgroundImageUrl} x={0} y={0} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} opacity={0.5} preserveAspectRatio="xMidYMid slice" pointerEvents="none" />
            )}

            {/* Catches a click/tap on empty canvas -- deselects in select
                tool, drops a pest pin in pest tool. Sits under every shape
                drawn after it, so a tap on an actual shape reaches that
                shape's own handler instead (SVG paints and hit-tests in
                document order). */}
            <rect x={0} y={0} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} fill="transparent" onPointerDown={handleBackgroundPointerDown} />

            {objects.map((obj) => {
              const hotspot = hotspotSeverity(obj, pestEvents);
              // Alpha suffix so a zone with no hotspot reads as a faint tint
              // over the dark canvas, not a solid bright block -- that
              // solid fill was exactly what made "Zone 1"/"Zone 2" labels
              // unreadable (light text on a bright light-blue fill).
              const zoneFill = hotspot ? `${SEVERITY_COLOR[hotspot]}55` : `${MAP_BLUE_FILL}2e`;
              const zoneStroke = selectedId === obj.id ? CANVAS_LINE : hotspot ? SEVERITY_COLOR[hotspot] : MAP_BLUE;
              const zoneStrokeWidth = selectedId === obj.id ? 3 : hotspot ? 2.5 : 1.5;
              const draggable = mode === "edit" && tool === "select";
              const isSelected = selectedId === obj.id;

              const labelNode = (cx: number, cy: number) =>
                obj.label ? (
                  <text
                    key={`${obj.id}-label`}
                    x={cx}
                    y={cy}
                    fontSize={CANVAS_TEXT.sm}
                    fill={CANVAS_LINE}
                    textAnchor="middle"
                    pointerEvents="none"
                  >
                    {obj.label}
                  </text>
                ) : null;

              if (obj.shapeType === "rect") {
                const { x = 0, y = 0, width = 0, height = 0, rotation = 0 } = obj.geometry;
                const transform = rotation ? `rotate(${rotation} ${x} ${y})` : undefined;
                return (
                  <g key={obj.id} transform={transform}>
                    <rect
                      x={x}
                      y={y}
                      width={width}
                      height={height}
                      fill={zoneFill}
                      stroke={zoneStroke}
                      strokeWidth={zoneStrokeWidth}
                      style={{ cursor: draggable ? "move" : "pointer" }}
                      onPointerDown={(e) => beginShapeDrag(e, obj.id, "move", obj.geometry)}
                      onPointerMove={onShapePointerMove}
                      onPointerUp={onShapePointerUp}
                    />
                    {labelNode(x + width / 2, y + height / 2 - 7)}
                    {isSelected && draggable && (
                      <rect
                        x={x + width - 6}
                        y={y + height - 6}
                        width={12}
                        height={12}
                        fill={CANVAS_LINE}
                        style={{ cursor: "nwse-resize" }}
                        onPointerDown={(e) => beginShapeDrag(e, obj.id, "resize", obj.geometry)}
                        onPointerMove={onShapePointerMove}
                        onPointerUp={onShapePointerUp}
                      />
                    )}
                  </g>
                );
              }
              if (obj.shapeType === "circle") {
                const { x = 0, y = 0, radius = 0 } = obj.geometry;
                return (
                  <g key={obj.id}>
                    <circle
                      cx={x}
                      cy={y}
                      r={radius}
                      fill={zoneFill}
                      stroke={zoneStroke}
                      strokeWidth={zoneStrokeWidth}
                      style={{ cursor: draggable ? "move" : "pointer" }}
                      onPointerDown={(e) => beginShapeDrag(e, obj.id, "move", obj.geometry)}
                      onPointerMove={onShapePointerMove}
                      onPointerUp={onShapePointerUp}
                    />
                    {labelNode(x, y - 7)}
                    {isSelected && draggable && (
                      <circle
                        cx={x + radius}
                        cy={y}
                        r={6}
                        fill={CANVAS_LINE}
                        style={{ cursor: "ew-resize" }}
                        onPointerDown={(e) => beginShapeDrag(e, obj.id, "resize", obj.geometry)}
                        onPointerMove={onShapePointerMove}
                        onPointerUp={onShapePointerUp}
                      />
                    )}
                  </g>
                );
              }
              if (obj.shapeType === "polygon") {
                const pts = obj.geometry.points ?? [];
                const n = pts.length / 2;
                const cx = n ? pts.filter((_, i) => i % 2 === 0).reduce((a, b) => a + b, 0) / n : 0;
                const cy = n ? pts.filter((_, i) => i % 2 === 1).reduce((a, b) => a + b, 0) / n : 0;
                const pointsAttr = pts.reduce<string[]>((acc, v, i) => {
                  if (i % 2 === 1) acc.push(`${pts[i - 1]},${v}`);
                  return acc;
                }, []).join(" ");
                return (
                  <g key={obj.id}>
                    <polygon
                      points={pointsAttr}
                      fill={zoneFill}
                      stroke={zoneStroke}
                      strokeWidth={zoneStrokeWidth}
                      style={{ cursor: draggable ? "move" : "pointer" }}
                      onPointerDown={(e) => beginShapeDrag(e, obj.id, "move", obj.geometry)}
                      onPointerMove={onShapePointerMove}
                      onPointerUp={onShapePointerUp}
                    />
                    {labelNode(cx, cy - 7)}
                  </g>
                );
              }
              if (obj.shapeType === "line") {
                const pts = obj.geometry.points ?? [];
                const pointsAttr = pts.reduce<string[]>((acc, v, i) => {
                  if (i % 2 === 1) acc.push(`${pts[i - 1]},${v}`);
                  return acc;
                }, []).join(" ");
                return (
                  <polyline
                    key={obj.id}
                    points={pointsAttr}
                    fill="none"
                    stroke={MAP_BLUE}
                    strokeWidth={obj.style?.strokeWidth ?? 4}
                    style={{ cursor: draggable ? "move" : "pointer" }}
                    onPointerDown={(e) => beginShapeDrag(e, obj.id, "move", obj.geometry)}
                    onPointerMove={onShapePointerMove}
                    onPointerUp={onShapePointerUp}
                  />
                );
              }
              return (
                <text
                  key={obj.id}
                  x={obj.geometry.x}
                  y={obj.geometry.y}
                  fill={CANVAS_LINE}
                  fontSize={CANVAS_TEXT.base}
                  style={{ cursor: draggable ? "move" : "pointer" }}
                  onPointerDown={(e) => beginShapeDrag(e, obj.id, "move", obj.geometry)}
                  onPointerMove={onShapePointerMove}
                  onPointerUp={onShapePointerUp}
                >
                  {obj.label ?? ""}
                </text>
              );
            })}

            {pestEvents
              .filter((ev) => ev.status === "active" && ev.x != null && ev.y != null)
              .flatMap((ev) => {
                const r = SEVERITY_RADIUS[ev.severity];
                const onActivate = (e: React.PointerEvent) => {
                  e.stopPropagation();
                  if (mode === "view") {
                    const overlapping = pestEvents.filter(
                      (other) =>
                        other.status === "active" &&
                        other.x != null &&
                        other.y != null &&
                        Math.hypot(other.x - ev.x!, other.y - ev.y!) <= OVERLAP_PX
                    );
                    if (overlapping.length > 1) setOverlapPicker(overlapping);
                    else router.push(`/app/facilities/${facilityId}/pest-events/${ev.id}`);
                  } else if (tool === "select") setSelectedEvent(ev);
                };
                const nodes: React.ReactNode[] = [];
                // Halo: a soft glow behind the pin if treated in the last
                // week -- "calming down," not a hard status like the ring.
                if (wasRecentlyTreated(ev.lastTreatedAt)) {
                  nodes.push(<circle key={`${ev.id}-halo`} cx={ev.x!} cy={ev.y!} r={r + 8} fill={MAP_BLUE} opacity={0.18} pointerEvents="none" />);
                }
                // Ring: a thin outer stroke, only drawn if a follow-up is
                // actually due -- absence of a ring is itself information.
                if (needsFollowUp(ev.createdAt)) {
                  nodes.push(
                    <circle
                      key={`${ev.id}-ring`}
                      cx={ev.x!}
                      cy={ev.y!}
                      r={r + 5}
                      fill="none"
                      stroke={CANVAS_LINE}
                      strokeWidth={1.5}
                      strokeDasharray="3 3"
                      pointerEvents="none"
                    />
                  );
                }
                nodes.push(
                  <circle
                    key={ev.id}
                    cx={ev.x!}
                    cy={ev.y!}
                    r={r}
                    fill={SEVERITY_COLOR[ev.severity]}
                    stroke={CANVAS_LINE}
                    strokeWidth={1.5}
                    style={{ cursor: "pointer" }}
                    onPointerDown={onActivate}
                  />
                );
                if (ev.trend === "up" || ev.trend === "down") {
                  nodes.push(
                    <text
                      key={`${ev.id}-trend`}
                      x={ev.x! + r + 2}
                      y={ev.y! - r - 2}
                      fontSize={CANVAS_TEXT.xs}
                      fill={ev.trend === "up" ? CANVAS_TREND_UP : CANVAS_TREND_DOWN}
                      pointerEvents="none"
                    >
                      {ev.trend === "up" ? "▲" : "▼"}
                    </text>
                  );
                }
                return nodes;
              })}
          </svg>

          {pestFormPos && (
            <div
              className="card absolute z-10 flex w-64 flex-col gap-2 p-3"
              style={{
                left: Math.min(pestFormPos.x * scale, CANVAS_WIDTH * scale - 260),
                top: Math.min(pestFormPos.y * scale, CANVAS_HEIGHT * scale - 180),
              }}
            >
              <div className="text-sm font-medium">New pest event</div>
              <input
                autoFocus
                value={pestSpecies}
                onChange={(e) => setPestSpecies(e.target.value)}
                placeholder="Pest species (e.g. thrips)"
                className="rounded-md border border-[var(--border)] bg-transparent px-2 py-1 text-sm"
              />
              <select
                value={pestSeverity}
                onChange={(e) => setPestSeverity(e.target.value as Severity)}
                className="rounded-md border border-[var(--border)] bg-transparent px-2 py-1 text-sm"
              >
                {(["low", "moderate", "high", "severe"] as const).map((s) => (
                  <option key={s} value={s}>
                    {s}
                  </option>
                ))}
              </select>
              <div className="flex gap-2">
                <button
                  onClick={submitPestEvent}
                  disabled={!pestSpecies.trim()}
                  className="flex-1 rounded-md bg-[var(--accent)] px-3 py-1.5 text-sm font-medium text-[var(--on-accent)] disabled:opacity-50"
                >
                  Drop pin
                </button>
                <button
                  onClick={() => {
                    setPestFormPos(null);
                    setTool("select");
                  }}
                  className="rounded-md border border-[var(--border)] px-3 py-1.5 text-sm text-[var(--text-dim)]"
                >
                  Cancel
                </button>
              </div>
            </div>
          )}

          {selectedEvent && (
            <div
              className="card absolute z-10 flex w-64 flex-col gap-2 p-3"
              style={{
                left: Math.min((selectedEvent.x ?? 0) * scale, CANVAS_WIDTH * scale - 260),
                top: Math.min((selectedEvent.y ?? 0) * scale, CANVAS_HEIGHT * scale - 140),
              }}
            >
              <div className="text-sm font-medium capitalize">{displayNameForPestSpecies(selectedEvent.pestSpecies)}</div>
              <div className="text-xs" style={{ color: SEVERITY_TEXT_COLOR[selectedEvent.severity] }}>
                {selectedEvent.severity} severity
              </div>
              {selectedEvent.notes && <div className="text-xs text-[var(--text-dim)]">{selectedEvent.notes}</div>}
              <Link href={`/app/facilities/${facilityId}/pest-events/${selectedEvent.id}`} className="text-xs text-[var(--accent-text)]">
                View details →
              </Link>
              <div className="flex gap-2">
                <button
                  onClick={resolveSelectedEvent}
                  className="min-h-11 flex-1 rounded-md bg-[var(--accent)] px-3 text-sm font-medium text-[var(--on-accent)]"
                >
                  Mark resolved
                </button>
                <button onClick={deleteSelectedEvent} className="min-h-11 rounded-md border border-[var(--danger)] px-3 text-sm text-[var(--danger)]">
                  Delete
                </button>
              </div>
              <button onClick={() => setSelectedEvent(null)} className="text-xs text-[var(--text-dim)]">
                Close
              </button>
            </div>
          )}

          {overlapPicker && (
            <div
              className="card absolute z-10 flex w-56 flex-col gap-1 p-2"
              style={{
                left: Math.min((overlapPicker[0].x ?? 0) * scale, CANVAS_WIDTH * scale - 232),
                top: Math.min((overlapPicker[0].y ?? 0) * scale, CANVAS_HEIGHT * scale - 40 * overlapPicker.length - 40),
              }}
            >
              <div className="px-1 text-xs text-[var(--text-dim)]">{overlapPicker.length} events here -- which one?</div>
              {overlapPicker.map((ev) => (
                <button
                  key={ev.id}
                  onClick={() => {
                    setOverlapPicker(null);
                    router.push(`/app/facilities/${facilityId}/pest-events/${ev.id}`);
                  }}
                  className="flex items-center justify-between gap-2 rounded-md px-2 py-1.5 text-left text-sm hover:bg-[var(--surface-raised)]"
                >
                  <span className="min-w-0 truncate capitalize">{displayNameForPestSpecies(ev.pestSpecies)}</span>
                  <span className="shrink-0 text-xs" style={{ color: SEVERITY_TEXT_COLOR[ev.severity] }}>
                    {ev.severity}
                  </span>
                </button>
              ))}
              <button onClick={() => setOverlapPicker(null)} className="px-1 text-left text-xs text-[var(--text-dim)]">
                Cancel
              </button>
            </div>
          )}
        </div>
      </div>
      {mode === "edit" && (
        <p className="text-xs text-[var(--text-dim)]">
          Select tool to drag an existing zone (or its corner/edge handle to resize) or click a pest pin. Pest event: click to drop a pin.
        </p>
      )}
    </div>
  );
}
