"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { Circle, Image as KonvaImage, Layer, Line, Rect, Stage, Text, Transformer } from "react-konva";
import type Konva from "konva";
import { CANVAS_TEXT } from "@/lib/canvas-text-scale";
import { SEVERITY_COLOR, type Severity } from "@/lib/colors";
import { pointInShape } from "@/lib/map-zones";
import { queuedFetch } from "@/lib/offline-queue";
import { useTheme } from "@/app/app/ThemeProvider";

// Freehand shape creation (rect/circle/polygon/label draw tools) was
// retired per Simon's direct call (map-redesign-plan.md, 2026-08-21) --
// tracing your own facility before getting any value was the wrong
// interaction model, and in practice everyone skipped it. New zones are
// generated by LayoutPicker's presets instead (../LayoutPicker.tsx); this
// component still renders/repositions/deletes whatever shapes already
// exist (generated or, for pre-existing areas, hand-drawn under the old
// system) and handles pin placement, just never creates a brand-new
// arbitrary shape from scratch anymore.
type ShapeType = "rect" | "circle" | "polygon" | "line" | "label";

interface Geometry {
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  radius?: number;
  rotation?: number;
  points?: number[];
}

interface MapObject {
  id: string;
  shapeType: ShapeType;
  geometry: Geometry;
  style: { fill?: string; stroke?: string; strokeWidth?: number } | null;
  label: string | null;
  zIndex: number;
}

interface Area {
  id: string;
  name: string;
  backgroundImageUrl: string | null;
  backgroundScale: number | null;
}


interface PestEvent {
  id: string;
  x: number | null;
  y: number | null;
  pestSpecies: string;
  severity: Severity;
  status: "active" | "resolved";
  notes: string | null;
  createdAt: string;
  lastTreatedAt: string | null;
  trend: "up" | "down" | "stable" | null;
}

const FOLLOW_UP_AFTER_DAYS = 3;
const RECENTLY_TREATED_DAYS = 7;
const DAY_MS = 86_400_000;
function needsFollowUp(createdAt: string): boolean {
  return Date.now() - new Date(createdAt).getTime() > FOLLOW_UP_AFTER_DAYS * DAY_MS;
}
function wasRecentlyTreated(lastTreatedAt: string | null): boolean {
  return lastTreatedAt != null && Date.now() - new Date(lastTreatedAt).getTime() < RECENTLY_TREATED_DAYS * DAY_MS;
}
// Bigger pin = worse severity -- one of the two always-on visual channels
// (color being the other), per the "glanceable, not click-to-learn" design
// direction. Ring/halo/arrow are secondary accents, only drawn when there's
// something to say, not competing dimensions on every pin.
const SEVERITY_RADIUS: Record<Severity, number> = { low: 7, moderate: 9.5, high: 12, severe: 15 };

const CANVAS_WIDTH = 900;
const CANVAS_HEIGHT = 600;
// Konva renders to canvas, not DOM, so it can't read CSS custom properties
// -- these have to match --map-blue/--map-blue-soft/--text in globals.css
// literally, per theme (useTheme() below), instead of one hardcoded set.
const CANVAS_COLORS = {
  light: { mapBlue: "#2f7fc4", mapBlueFill: "#eaf3fb", line: "#1c2431", trendUp: "#c1502e", trendDown: "#2f8f6e" },
  dark: { mapBlue: "#7ec4f0", mapBlueFill: "#bfe3fa", line: "#ffffff", trendUp: "#ce5d40", trendDown: "#4e9e86" },
} as const;
const SEVERITY_RANK: Record<Severity, number> = { low: 0, moderate: 1, high: 2, severe: 3 };

// Every drawn zone is the same calm light blue by default -- color is a
// hotspot signal, not a decoration a grower picks per-shape. If an active
// pest event's pin falls inside a zone, that zone tints to the worst
// severity found inside it instead.
function hotspotSeverity(obj: MapObject, events: PestEvent[]): Severity | null {
  let worst: Severity | null = null;
  for (const ev of events) {
    if (ev.status !== "active" || ev.x == null || ev.y == null) continue;
    if (!pointInShape(ev.x, ev.y, obj.shapeType, obj.geometry)) continue;
    if (!worst || SEVERITY_RANK[ev.severity] > SEVERITY_RANK[worst]) worst = ev.severity;
  }
  return worst;
}

function useBackgroundImage(url: string | null) {
  const [image, setImage] = useState<HTMLImageElement | null>(null);
  useEffect(() => {
    if (!url) return;
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.src = url;
    img.onload = () => setImage(img);
    // Runs on cleanup (dependency change or unmount), not synchronously in
    // the effect body -- clears the stale image while a new one loads, or
    // when url goes back to null.
    return () => setImage(null);
  }, [url]);
  return image;
}

export default function MapEditor({
  facilityId,
  area,
  initialObjects,
  initialPestEvents,
}: {
  facilityId: string;
  area: Area;
  initialObjects: MapObject[];
  initialPestEvents: PestEvent[];
}) {
  const router = useRouter();
  const { theme } = useTheme();
  const { mapBlue: MAP_BLUE, mapBlueFill: MAP_BLUE_FILL, line: CANVAS_LINE, trendUp: CANVAS_TREND_UP, trendDown: CANVAS_TREND_DOWN } = CANVAS_COLORS[theme];
  const [mode, setMode] = useState<"view" | "edit">("view");
  const [objects, setObjects] = useState<MapObject[]>(initialObjects);
  const [pestEvents, setPestEvents] = useState<PestEvent[]>(initialPestEvents);
  const [tool, setTool] = useState<"select" | "pest">("select");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [uploading, setUploading] = useState(false);
  const [pestFormPos, setPestFormPos] = useState<{ x: number; y: number } | null>(null);
  const [pestSpecies, setPestSpecies] = useState("");
  const [pestSeverity, setPestSeverity] = useState<Severity>("moderate");
  const [selectedEvent, setSelectedEvent] = useState<PestEvent | null>(null);

  const bgImage = useBackgroundImage(area.backgroundImageUrl);
  const transformerRef = useRef<Konva.Transformer>(null);
  const shapeRefs = useRef<Map<string, Konva.Node>>(new Map());
  const containerRef = useRef<HTMLDivElement>(null);

  // The canvas's internal coordinate system stays a fixed 900x600 (every
  // shape's x/y/width/height is stored in that space) -- only how it's
  // *rendered* shrinks to fit narrower viewports, via Konva's own
  // scaleX/scaleY on the Stage. Without this, a 900px-wide canvas overflows
  // any container narrower than that and gets clipped on the right, which
  // is exactly the "square gets cut off as I move it right" bug: the shape
  // was never actually off-canvas, the canvas itself just didn't fit.
  const [baseScale, setBaseScale] = useState(1);
  useEffect(() => {
    const el = containerRef.current;
    if (!el) return;
    const observer = new ResizeObserver(([entry]) => {
      // Capped at 1.4x, not 1x -- the map should fill most of its card on
      // a normal desktop width, not stay pinned to 900px with dead space
      // around it, but an ultrawide monitor shouldn't blow it up absurdly.
      setBaseScale(Math.min(1.4, entry.contentRect.width / CANVAS_WIDTH));
    });
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  // User-driven zoom multiplier on top of the responsive baseScale above --
  // separate state so a container resize (which recomputes baseScale) never
  // clobbers a zoom level the grower is actively using. Page-wide native
  // pinch/double-tap zoom is disabled (app/layout.tsx's viewport export,
  // ticket C2), so this + the touch pinch handler below are what replace it
  // specifically for the map.
  const MIN_ZOOM = 1;
  const MAX_ZOOM = 3;
  const [zoom, setZoom] = useState(1);
  const scale = baseScale * zoom;
  const pinchState = useRef<{ distance: number; zoom: number } | null>(null);

  function touchDistance(touches: TouchList): number {
    const [a, b] = [touches[0], touches[1]];
    return Math.hypot(b.clientX - a.clientX, b.clientY - a.clientY);
  }

  function handleTouchMove(e: Konva.KonvaEventObject<TouchEvent>) {
    const touches = e.evt.touches;
    if (touches.length !== 2) {
      pinchState.current = null;
      return;
    }
    e.evt.preventDefault();
    const distance = touchDistance(touches);
    if (!pinchState.current) {
      pinchState.current = { distance, zoom };
      return;
    }
    const next = (pinchState.current.zoom * distance) / pinchState.current.distance;
    setZoom(Math.min(MAX_ZOOM, Math.max(MIN_ZOOM, next)));
  }

  function handleTouchEnd(e: Konva.KonvaEventObject<TouchEvent>) {
    if (e.evt.touches.length < 2) pinchState.current = null;
  }

  const base = `/api/facilities/${facilityId}/areas/${area.id}`;
  const eventsBase = `/api/facilities/${facilityId}/pest-events`;

  useEffect(() => {
    if (!transformerRef.current) return;
    const node = selectedId ? shapeRefs.current.get(selectedId) : null;
    transformerRef.current.nodes(node ? [node] : []);
    transformerRef.current.getLayer()?.batchDraw();
  }, [selectedId, objects]);

  async function updateGeometry(id: string, geometry: Geometry) {
    setObjects((prev) => prev.map((o) => (o.id === id ? { ...o, geometry } : o)));
    await queuedFetch(`${base}/objects/${id}`, { geometry }, "Map edit", "PATCH");
  }

  async function deleteSelected() {
    if (!selectedId) return;
    await fetch(`${base}/objects/${selectedId}`, { method: "DELETE" });
    setObjects((prev) => prev.filter((o) => o.id !== selectedId));
    setSelectedId(null);
  }

  async function submitPestEvent() {
    if (!pestFormPos || !pestSpecies.trim()) return;
    const res = await fetch(eventsBase, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        facilityAreaId: area.id,
        x: pestFormPos.x,
        y: pestFormPos.y,
        pestSpecies: pestSpecies.trim(),
        severity: pestSeverity,
      }),
    });
    if (res.ok) {
      const row = await res.json();
      setPestEvents((prev) => [...prev, row]);
    }
    setPestFormPos(null);
    setPestSpecies("");
    setPestSeverity("moderate");
    setTool("select");
  }

  async function resolveSelectedEvent() {
    if (!selectedEvent) return;
    const res = await fetch(`${eventsBase}/${selectedEvent.id}`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: "resolved" }),
    });
    if (res.ok) {
      setPestEvents((prev) => prev.map((ev) => (ev.id === selectedEvent.id ? { ...ev, status: "resolved" } : ev)));
    }
    setSelectedEvent(null);
  }

  async function deleteSelectedEvent() {
    if (!selectedEvent) return;
    await fetch(`${eventsBase}/${selectedEvent.id}`, { method: "DELETE" });
    setPestEvents((prev) => prev.filter((ev) => ev.id !== selectedEvent.id));
    setSelectedEvent(null);
  }

  async function handleBackgroundUpload(e: React.ChangeEvent<HTMLInputElement>) {
    const file = e.target.files?.[0];
    if (!file) return;
    setUploading(true);
    const form = new FormData();
    form.append("file", file);
    const res = await fetch(`${base}/background`, { method: "POST", body: form });
    setUploading(false);
    if (res.ok) window.location.reload(); // simplest way to refresh the loaded background image
  }

  function stagePos(e: Konva.KonvaEventObject<MouseEvent>) {
    const stage = e.target.getStage();
    // getPointerPosition() returns raw container pixels, not adjusted for
    // the stage's own scaleX/scaleY -- with the responsive scale added
    // above, that would land every drawn shape/dropped pin in the wrong
    // spot whenever scale != 1. getRelativePointerPosition() accounts for
    // the stage's full transform, giving back real 900x600-space
    // coordinates regardless of how small the stage is currently rendered.
    return stage?.getRelativePointerPosition() ?? { x: 0, y: 0 };
  }

  function handleMouseDown(e: Konva.KonvaEventObject<MouseEvent>) {
    if (mode === "view") return; // view mode has no selection tools -- pins handle their own click
    if (tool === "select") {
      if (e.target === e.target.getStage()) {
        setSelectedId(null);
        setSelectedEvent(null);
      }
      return;
    }
    if (tool === "pest") {
      setPestFormPos(stagePos(e));
    }
  }

  return (
    <div ref={containerRef} className="flex flex-col gap-3">
      <div className="flex items-center justify-end">
        <button
          onClick={() => {
            setMode((m) => (m === "view" ? "edit" : "view"));
            setSelectedId(null);
            setSelectedEvent(null);
            setTool("select");
          }}
          className={`rounded-md border px-3 py-1.5 text-sm ${
            mode === "edit" ? "border-[var(--accent)] text-[var(--accent)]" : "border-[var(--border)] text-[var(--text-dim)]"
          }`}
        >
          {mode === "edit" ? "Done editing" : "Edit site layout"}
        </button>
      </div>

      {/* Precision drag/resize editing on a Konva canvas is genuinely hard
          one-handed on a phone -- a deliberate, confirmed call (spike
          rec: no code gate exists or should exist, since a tablet/laptop
          touchscreen can be perfectly fine; this is just an honest heads-up
          on the narrow-viewport case, not a block). The abstract bay-bar
          heatmap on the dashboard covers day-to-day mobile use instead. */}
      {mode === "edit" && (
        <div className="card p-3 text-xs text-[var(--text-dim)] lg:hidden">
          Precise layout editing works best on a larger screen. For a quick check in the field, the bay heatmap on Home covers most day-to-day use.
        </div>
      )}

      {mode === "edit" && (
        <div className="flex flex-wrap items-center gap-2">
          {(["select", "pest"] as const).map((t) => (
            <button
              key={t}
              onClick={() => {
                setTool(t);
                setPestFormPos(null);
              }}
              className={`rounded-md border px-3 py-1.5 text-sm capitalize ${
                tool === t ? "border-[var(--accent)] text-[var(--accent)]" : "border-[var(--border)] text-[var(--text-dim)]"
              }`}
            >
              {t === "pest" ? "Pest event" : t}
            </button>
          ))}
          {selectedId && (
            <button onClick={deleteSelected} className="rounded-md border border-[var(--danger)] px-3 py-1.5 text-sm text-[var(--danger)]">
              Delete selected
            </button>
          )}
          <label className="ml-auto cursor-pointer rounded-md border border-[var(--border)] px-3 py-1.5 text-sm text-[var(--text-dim)]">
            {uploading ? "Uploading…" : "Upload blueprint/background"}
            <input type="file" accept="image/*" className="hidden" onChange={handleBackgroundUpload} />
          </label>
        </div>
      )}

      {/* Explicit pixel size, not "shrink to fit content" -- this div is a
          flex-column child, and flex's default align-items:stretch would
          otherwise stretch it to the full width of its parent (which can be
          wider than the Stage's actual rendered size), leaving the Stage
          -- and everything drawn on it -- pushed into the left portion of a
          too-wide bordered frame. That mismatch was the real cause of "zones
          crushed to the left," not a spacing bug in the zones themselves. */}
      {/* Zoom buttons are the primary control (reliable on every device);
          the Stage below also handles real two-finger pinch on touch
          devices, both replacing the native pinch this page disables
          (ticket C2). overflow-auto lets a zoomed-in map be panned by
          scroll/drag, same as any oversized scrollable content. */}
      <div className="flex items-center gap-2 self-end">
        <button
          type="button"
          onClick={() => setZoom((z) => Math.max(MIN_ZOOM, z - 0.25))}
          disabled={zoom <= MIN_ZOOM}
          className="rounded-md border border-[var(--border)] px-2.5 py-1 text-sm text-[var(--text-dim)] disabled:opacity-40"
        >
          −
        </button>
        <span className="label-mono w-10 text-center">{Math.round(zoom * 100)}%</span>
        <button
          type="button"
          onClick={() => setZoom((z) => Math.min(MAX_ZOOM, z + 0.25))}
          disabled={zoom >= MAX_ZOOM}
          className="rounded-md border border-[var(--border)] px-2.5 py-1 text-sm text-[var(--text-dim)] disabled:opacity-40"
        >
          +
        </button>
      </div>

      <div className="max-w-full overflow-auto">
        <div className="relative map-canvas-frame" style={{ width: CANVAS_WIDTH * scale, height: CANVAS_HEIGHT * scale }}>
        <div className="map-canvas-grid" />
        <Stage
          width={CANVAS_WIDTH * scale}
          height={CANVAS_HEIGHT * scale}
          scaleX={scale}
          scaleY={scale}
          onMouseDown={handleMouseDown}
          onTouchMove={handleTouchMove}
          onTouchEnd={handleTouchEnd}
        >
          <Layer>
            {bgImage && (
              <KonvaImage image={bgImage} width={CANVAS_WIDTH} height={CANVAS_HEIGHT} opacity={0.5} listening={false} />
            )}

            {objects.map((obj) => {
              // key AND ref must be literal JSX attributes on each element
              // below, not spread via this object -- both are extracted by
              // the JSX compiler statically, not read out of a merged props
              // object at runtime, so either one arriving only via {...spread}
              // silently fails to do its job (no reconciliation key, no ref
              // callback ever fires).
              const nodeRef = (node: Konva.Node | null) => {
                if (node) shapeRefs.current.set(obj.id, node);
                else shapeRefs.current.delete(obj.id);
              };
              const commonProps = {
                draggable: mode === "edit" && tool === "select",
                onClick: () => mode === "edit" && tool === "select" && setSelectedId(obj.id),
                onTap: () => mode === "edit" && tool === "select" && setSelectedId(obj.id),
                onDragEnd: (e: Konva.KonvaEventObject<DragEvent>) =>
                  updateGeometry(obj.id, { ...obj.geometry, x: e.target.x(), y: e.target.y() }),
                onTransformEnd: (e: Konva.KonvaEventObject<Event>) => {
                  const node = e.target;
                  updateGeometry(obj.id, {
                    ...obj.geometry,
                    x: node.x(),
                    y: node.y(),
                    width: (obj.geometry.width ?? 0) * node.scaleX(),
                    height: (obj.geometry.height ?? 0) * node.scaleY(),
                    radius: obj.geometry.radius ? obj.geometry.radius * node.scaleX() : undefined,
                    rotation: node.rotation(),
                  });
                  node.scaleX(1);
                  node.scaleY(1);
                },
              };

              const hotspot = hotspotSeverity(obj, pestEvents);
              // Alpha suffix so a zone with no hotspot reads as a faint tint
              // over the dark canvas, not a solid bright block -- that
              // solid fill was exactly what made "Zone 1"/"Zone 2" labels
              // unreadable (light text on a bright light-blue fill).
              const zoneFill = hotspot ? `${SEVERITY_COLOR[hotspot]}55` : `${MAP_BLUE_FILL}2e`;
              const zoneStroke = selectedId === obj.id ? CANVAS_LINE : hotspot ? SEVERITY_COLOR[hotspot] : MAP_BLUE;
              const zoneStrokeWidth = selectedId === obj.id ? 3 : hotspot ? 2.5 : 1.5;

              // A zone's name isn't visible unless it's rendered as its own
              // text -- unlike the dedicated "label" shape type, rect/circle/
              // polygon zones don't have anywhere else to show it. Rendered
              // as a plain sibling Text recomputed from the same geometry
              // each render, not attached to the shape via a Group, so
              // dragging/resizing the zone doesn't need extra transform math.
              const labelNode = (cx: number, cy: number) =>
                obj.label ? (
                  <Text
                    key={`${obj.id}-label`}
                    x={cx}
                    y={cy}
                    text={obj.label}
                    fontSize={CANVAS_TEXT.sm}
                    fill={CANVAS_LINE}
                    align="center"
                    offsetX={obj.label.length * 3.5}
                    listening={false}
                  />
                ) : null;

              if (obj.shapeType === "rect") {
                const { x = 0, y = 0, width = 0, height = 0 } = obj.geometry;
                return [
                  <Rect
                    key={obj.id}
                    ref={nodeRef}
                    {...commonProps}
                    x={x}
                    y={y}
                    width={width}
                    height={height}
                    rotation={obj.geometry.rotation ?? 0}
                    fill={zoneFill}
                    stroke={zoneStroke}
                    strokeWidth={zoneStrokeWidth}
                  />,
                  labelNode(x + width / 2, y + height / 2 - 7),
                ];
              }
              if (obj.shapeType === "circle") {
                const { x = 0, y = 0 } = obj.geometry;
                return [
                  <Circle
                    key={obj.id}
                    ref={nodeRef}
                    {...commonProps}
                    x={x}
                    y={y}
                    radius={obj.geometry.radius}
                    fill={zoneFill}
                    stroke={zoneStroke}
                    strokeWidth={zoneStrokeWidth}
                  />,
                  labelNode(x, y - 7),
                ];
              }
              if (obj.shapeType === "polygon") {
                const pts = obj.geometry.points ?? [];
                const n = pts.length / 2;
                const cx = n ? pts.filter((_, i) => i % 2 === 0).reduce((a, b) => a + b, 0) / n : 0;
                const cy = n ? pts.filter((_, i) => i % 2 === 1).reduce((a, b) => a + b, 0) / n : 0;
                return [
                  <Line
                    key={obj.id}
                    ref={nodeRef}
                    {...commonProps}
                    points={pts}
                    closed
                    fill={zoneFill}
                    stroke={zoneStroke}
                    strokeWidth={zoneStrokeWidth}
                  />,
                  labelNode(cx, cy - 7),
                ];
              }
              if (obj.shapeType === "line") {
                return (
                  <Line
                    key={obj.id}
                    ref={nodeRef}
                    {...commonProps}
                    points={obj.geometry.points}
                    stroke={MAP_BLUE}
                    strokeWidth={obj.style?.strokeWidth ?? 4}
                  />
                );
              }
              return (
                <Text
                  key={obj.id}
                  ref={nodeRef}
                  {...commonProps}
                  x={obj.geometry.x}
                  y={obj.geometry.y}
                  text={obj.label ?? ""}
                  fill={CANVAS_LINE}
                  fontSize={CANVAS_TEXT.base}
                />
              );
            })}

            {pestEvents
              .filter((ev) => ev.status === "active" && ev.x != null && ev.y != null)
              .flatMap((ev) => {
                const r = SEVERITY_RADIUS[ev.severity];
                const onActivate = () => {
                  if (mode === "view") router.push(`/app/facilities/${facilityId}/pest-events/${ev.id}`);
                  else if (tool === "select") setSelectedEvent(ev);
                };
                const nodes: React.ReactNode[] = [];
                // Halo: a soft glow behind the pin if treated in the last
                // week -- "calming down," not a hard status like the ring.
                if (wasRecentlyTreated(ev.lastTreatedAt)) {
                  nodes.push(
                    <Circle
                      key={`${ev.id}-halo`}
                      x={ev.x!}
                      y={ev.y!}
                      radius={r + 8}
                      fill={MAP_BLUE}
                      opacity={0.18}
                      listening={false}
                    />
                  );
                }
                // Ring: a thin outer stroke, only drawn if a follow-up is
                // actually due -- absence of a ring is itself information.
                if (needsFollowUp(ev.createdAt)) {
                  nodes.push(
                    <Circle
                      key={`${ev.id}-ring`}
                      x={ev.x!}
                      y={ev.y!}
                      radius={r + 5}
                      stroke={CANVAS_LINE}
                      strokeWidth={1.5}
                      dash={[3, 3]}
                      listening={false}
                    />
                  );
                }
                nodes.push(
                  <Circle
                    key={ev.id}
                    x={ev.x!}
                    y={ev.y!}
                    radius={r}
                    fill={SEVERITY_COLOR[ev.severity]}
                    stroke={CANVAS_LINE}
                    strokeWidth={1.5}
                    onClick={onActivate}
                    onTap={onActivate}
                  />
                );
                if (ev.trend === "up" || ev.trend === "down") {
                  nodes.push(
                    <Text
                      key={`${ev.id}-trend`}
                      x={ev.x! + r + 2}
                      y={ev.y! - r - 2}
                      text={ev.trend === "up" ? "▲" : "▼"}
                      fontSize={CANVAS_TEXT.xs}
                      fill={ev.trend === "up" ? CANVAS_TREND_UP : CANVAS_TREND_DOWN}
                      listening={false}
                    />
                  );
                }
                return nodes;
              })}

            <Transformer ref={transformerRef} rotateEnabled />
          </Layer>
        </Stage>

        {pestFormPos && (
          <div
            className="card absolute z-10 flex w-64 flex-col gap-2 p-3"
            style={{
              left: Math.min(pestFormPos.x * scale, CANVAS_WIDTH * scale - 260),
              top: Math.min(pestFormPos.y * scale, CANVAS_HEIGHT * scale - 180),
            }}
          >
            <div className="text-sm font-medium">New pest event</div>
            <input
              autoFocus
              value={pestSpecies}
              onChange={(e) => setPestSpecies(e.target.value)}
              placeholder="Pest species (e.g. thrips)"
              className="rounded-md border border-[var(--border)] bg-transparent px-2 py-1 text-sm"
            />
            <select
              value={pestSeverity}
              onChange={(e) => setPestSeverity(e.target.value as Severity)}
              className="rounded-md border border-[var(--border)] bg-transparent px-2 py-1 text-sm"
            >
              {(["low", "moderate", "high", "severe"] as const).map((s) => (
                <option key={s} value={s}>
                  {s}
                </option>
              ))}
            </select>
            <div className="flex gap-2">
              <button
                onClick={submitPestEvent}
                disabled={!pestSpecies.trim()}
                className="flex-1 rounded-md bg-[var(--accent)] px-3 py-1.5 text-sm font-medium text-[var(--on-accent)] disabled:opacity-50"
              >
                Drop pin
              </button>
              <button
                onClick={() => {
                  setPestFormPos(null);
                  setTool("select");
                }}
                className="rounded-md border border-[var(--border)] px-3 py-1.5 text-sm text-[var(--text-dim)]"
              >
                Cancel
              </button>
            </div>
          </div>
        )}

        {selectedEvent && (
          <div
            className="card absolute z-10 flex w-64 flex-col gap-2 p-3"
            style={{
              left: Math.min((selectedEvent.x ?? 0) * scale, CANVAS_WIDTH * scale - 260),
              top: Math.min((selectedEvent.y ?? 0) * scale, CANVAS_HEIGHT * scale - 140),
            }}
          >
            <div className="text-sm font-medium capitalize">{selectedEvent.pestSpecies}</div>
            <div className="text-xs" style={{ color: SEVERITY_COLOR[selectedEvent.severity] }}>
              {selectedEvent.severity} severity
            </div>
            {selectedEvent.notes && <div className="text-xs text-[var(--text-dim)]">{selectedEvent.notes}</div>}
            <Link href={`/app/facilities/${facilityId}/pest-events/${selectedEvent.id}`} className="text-xs text-[var(--accent)]">
              View details →
            </Link>
            <div className="flex gap-2">
              <button
                onClick={resolveSelectedEvent}
                className="flex-1 rounded-md bg-[var(--accent)] px-3 py-1.5 text-sm font-medium text-[var(--on-accent)]"
              >
                Mark resolved
              </button>
              <button onClick={deleteSelectedEvent} className="rounded-md border border-[var(--danger)] px-3 py-1.5 text-sm text-[var(--danger)]">
                Delete
              </button>
            </div>
            <button onClick={() => setSelectedEvent(null)} className="text-xs text-[var(--text-dim)]">
              Close
            </button>
          </div>
        )}
        </div>
      </div>
      {mode === "edit" && (
        <p className="text-xs text-[var(--text-dim)]">
          Select tool to drag/resize an existing zone or click a pest pin. Pest event: click to drop a pin.
        </p>
      )}
    </div>
  );
}
